---
- systemd-boot
- dracut-core
- linux-image-arm64
- ca-certificates
- vim
- sudo
- net-tools
- openssh-client
- openssh-server
- procps
- less
- dbus
- policykit-1
- curl
- wget
- ca-certificates
- apt-transport-https
- iproute2
- iputils-ping
- traceroute
- usbutils
- zstd
- firmware-misc-nonfree
